# @package agent
name: baku
_target_: agent.baku.BCAgent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
hidden_dim: ${suite.hidden_dim}
stddev_schedule: 0.1
stddev_clip: 0.3
use_tb: ${use_tb}
augment: True
obs_type: ${obs_type}
encoder_type: ${encoder_type}
policy_type: gpt
policy_head: deterministic
pixel_keys: ${suite.pixel_keys}
feature_key: ${suite.feature_key}
use_proprio: false
train_encoder: true
norm: false
history: ${suite.history}
history_len: ${suite.history_len}
eval_history_len: ${suite.eval_history_len}
separate_encoders: false # have a separate encoder for each pixel key
temporal_agg: ${temporal_agg}
max_episode_len: ${suite.task_make_fn.max_episode_len}
num_queries: ${num_queries}
use_language: ${use_language}
prompt: ${prompt}
film: false

bc_dataset:
  _target_: utils.read_data.BCDataset
  path: ${suite.data_path}
  tasks: ${suite.task.tasks}
  num_demos_per_task: 1
  obs_type: ${obs_type}
  history: false
  history_len: ${suite.history_len}
  prompt: ${prompt}
  temporal_agg: ${temporal_agg}
  num_queries: ${num_queries}
  img_size: 84
  intermediate_goal_step: 30
  store_actions: true
  pixel_keys: ${suite.pixel_keys}
  #subsample: none

